apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8staging.liftright.dirigim.us
    http:
      paths: /v1/*
      - backend:
          serviceName: lrds
          servicePort: 80
